sudo: false
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - texinfo
script: 
  - sed -i '' -e 's/1.14/1.11/' configure.ac
  - ([ -d m4 ] || mkdir m4) && autoreconf -i && ./configure && make && make check
